// !?!?!?!?!?!?!?!?!?!?!?!?!?!?!?!?!
// !?!?!? WARNING CONTRIBUTOR ?!?!?!
// !?!?!?!?!?!?!?!?!?!?!?!?!?!?!?!?!
// this file is generated by tools/generator.c
// please edit that file and regenerate this one if you want to make edits

#ifndef _HMATHS_MATHS_H_
#define _HMATHS_MATHS_H_

#include "types.h"
#include "scalar.h"
#include "vector.h"
#include "matrix.h"

#endif // _HMATHS_MATHS_H_
